[tool.roo]
[[tool.roo.source]]
name = "CRAN"
url = "https://cloud.r-project.org/"

[tool.roo.dependencies]
exceptions = "*"

[tool.roo.dev-dependencies]
pkgdown = "1.6.1"
testthat = "*"
roxygen2 = "*"
lintr = "*"
devtools = "2.4.3"
here = "*"
covr = "*"
knitr = "*"
# DT and htmltools needed by covr to generate the table
DT = "*"
htmltools = "*"
mockery = "*"
rmarkdown = "*"
